### ISSUE TITLE
How to use storyboard for slide menu?

### ISSUE THREAD

**Issue by RahulM1987** [HongliYu/DPSlideMenuKit-Swift#1]
I can see you have 

```
init(nibName nibNameOrNil: String?,
                        bundle nibBundleOrNil: Bundle?)
```

But i want to use storyboard and not XIB by setting the StoryBoard ID it will not work so is it possible to use storyboard in you slide menu?

**Comment by HongliYu** [comment]
@RahulM1987 , support of storyboard will be added in the next version, may be next week. I am still on holiday :)

**Comment by HongliYu** [comment]
@RahulM1987, version 0.1.0 released, add support to StoryBoard(check the demo), and updated to Swift 3.0
