### ISSUE TITLE
Disable/Remove Right menu

### ISSUE THREAD

**Issue by lethianqt94** [HongliYu/DPSlideMenuKit-Swift#13]
I don't need to use Right menu, so how can I remove or disable it?

**Comment by HongliYu** [comment]
@lethianqt94  It's a bug. I update the code, check the new version 0.2.5. Now you can just set nil in DPSlideMenuManager.shared.setup function. You can disable left side, right side or both of them. have a nice day ;)

**Comment by ranjtha20** [comment]
can we setup controller in programatically?not using storyboard.

**Comment by HongliYu** [comment]
@ranjtha20 You can set up everything manually with out storyboard now. I just updated the library, with swift 4.2, meanwhile support all iPhone devices.

**Comment by ranjtha20** [comment]
@HongliYu  Thank You
