### ISSUE TITLE
How to implement this without using storyboard

### ISSUE THREAD

**Issue by nicoaureliovillanueva** [HongliYu/DPSlideMenuKit-Swift#3]
Hi Great work!

But I wonder how to implement this side menu without using storyboard?
Im currently using xibs for my project. Im also using swift 3

Thanks! :)

**Comment by HongliYu** [comment]
@nicoaureliovillanueva Check the demo, and focus this words:  // not embed in storyboard? add it manually

**Comment by nicoaureliovillanueva** [comment]
owww! thanks for this @HongliYu!!! More Powers!
