### ISSUE TITLE
Using Navigationcontroller

### ISSUE THREAD

**Issue by trungnguyen1791** [HongliYu/DPSlideMenuKit-Swift#4]
Hi, 

Thanks for your great library.
I just have one question, how can I use uinavigationcontroller here?
Currently, I only see a method to create leftmenu with centerVC's type = DPContentViewController.

Thanks

**Comment by HongliYu** [comment]
@trungnguyen1791 Where and how are you trying to use uinavigationcontroller? Need more details

**Comment by ashu1702** [comment]
@HongliYu : I am also trying the same. My understanding so far is that this lib requires every controller to be the subclass of DPContentViewController but if i want my ViewController to be able to show detail view controller how can i push another controller from DPContentViewController as it doesn't have any NavigationController and i don't see an easy way to add navigation to it without changing your lib code. Please advise.

**Comment by HongliYu** [comment]
@ashu1702  Check the demo project in version 0.2.2, just like Slack. No matter which page you go, there is only one page in the center, if you want to change the center view responding to left or right item's selecting action, the view controller should be inherited from DPCenterContentViewController. And if you want to go deeply into somewhere among one of the center views, try to build a new NavigationController to take control of the new view controllers stack.
