### ISSUE TITLE
Question: Possibility to add picture/image?

### ISSUE THREAD

**Issue by calvinorchiz** [HongliYu/DPSlideMenuKit-Swift#5]
Thanks for the great library - the menu looks really good.

Is it possible to add a image/picture to the menu?

**Comment by HongliYu** [comment]
@calvinorchiz Actually, I am trying to make a slide menu just like Slack iOS Client. Surely, I will consider your opinion. Thanks for your attention

**Comment by tariq235** [comment]
+1 Any update on this ticket ?

**Comment by HongliYu** [comment]
@calvinorchiz  Check the new version, it's all up to you now😊
